version: '3.8'

services:
  postgres:
    container_name: postgres_cities_api
    image: postgres
    env_file:
    # Read Keys from dotEnv
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  postgres: